# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Reinforcer < Formula
  desc "A codegen tool for easy adoption of resiliency patterns in Go"
  homepage "https://github.com/csueiras/reinforcer"
  version "0.3.3-alpha"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/csueiras/reinforcer/releases/download/v0.3.3-alpha/reinforcer_0.3.3-alpha_Darwin_x86_64.tar.gz"
    sha256 "8c0300612b62378346a88aa0e05cb0b2b090e09c09503f04ffa1bf83a7320dcd"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/csueiras/reinforcer/releases/download/v0.3.3-alpha/reinforcer_0.3.3-alpha_Linux_x86_64.tar.gz"
    sha256 "597a6dce77776d56adcfb230ecb3601ab033426e76ce542f2105092fad726eee"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/csueiras/reinforcer/releases/download/v0.3.3-alpha/reinforcer_0.3.3-alpha_Linux_arm64.tar.gz"
    sha256 "15720923556e3cb44e6b19cbc0861c2b8d70af0eb5d34b8497160b16f9f8d29b"
  end

  def install
    bin.install "reinforcer"
  end

  test do
    system "#{bin}reinforcer --version"
  end
end
