# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Reinforcer < Formula
  desc "Codegen tool for easy adoption of resiliency patterns in Go"
  homepage "https://github.com/csueiras/reinforcer"
  version "0.7.2"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/csueiras/reinforcer/releases/download/v0.7.2/reinforcer_0.7.2_Darwin_x86_64.tar.gz"
    sha256 "56a2f0668a60b6c8104cd58fb94b870a60b2807d0ecc4a4e5faa03581b57f543"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/csueiras/reinforcer/releases/download/v0.7.2/reinforcer_0.7.2_Linux_x86_64.tar.gz"
    sha256 "2b54220656925e24dbf431ecab8d84fc33a414ebc5d88a9670102eae7cab532e"
  end

  def install
    bin.install "reinforcer"
  end

  test do
    system "#{bin}reinforcer --version"
  end
end
